name: Publish README to User Homepage

on:
  push:
    branches: [ main ]
    paths:
      - "README.md"
      - ".github/workflows/publish-readme-to-homepage.yml"
      - "site/**"
      - "assets/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up working directories
        run: |
          mkdir -p dist
          cp README.md dist/README.md

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert README.md to HTML
        run: |
          pandoc \
            --from=gfm \
            --to=html5 \
            --standalone \
            --metadata title="Field Linguistics Extension Tools (FLET)" \
            --template=site/template.html \
            -o dist/index.html \
            dist/README.md

      - name: Copy static assets
        run: |
          cp site/styles.css dist/styles.css
          mkdir -p dist/assets
          cp assets/logo-flet.svg dist/assets/logo-flet.svg
          cp assets/favicon.svg dist/favicon.svg || true
          touch dist/.nojekyll

      - name: Deploy to user site repository (rulingants.github.io)
        env:
          TARGET_REPO: rulingAnts/rulingants.github.io
          GH_TOKEN: ${{ secrets.PUBLISH_README_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "Missing secret PUBLISH_README_TOKEN. Please add it in repo settings."
            exit 1
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 "https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git" site-repo
          cd site-repo
          # Preserve CNAME if present
          if [ -f CNAME ]; then cp CNAME ../dist/CNAME; fi
          rm -rf ./*
          cp -R ../dist/* .
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to publish."
            exit 0
          fi
          default_branch=$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@')
          git commit -m "Auto-publish FLET README as homepage"
          git push origin HEAD:${default_branch}
